export { default as changeDim } from './change_dim';
export { default as changePlayers } from './change_players';
export { default as changeTheme } from './change_theme';
export { default as changeToWin } from './change_to_win';
export { default as makeMove } from './make_move';
export { default as redo } from './redo';
export { default as redoAll } from './redo_all';
export { default as undo } from './undo';
export { default as undoAll } from './undo_all';